routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('mailPreview',['as' => 'mailPreview','uses' => 'MailController@mailPreview']);
Route::get('interactionCount',['as' => 'interactionCount','uses' => 'Inbound\inboundController@interactionCount']);

Route::get('testingcron',['as' => 'testingcron','uses' => 'CronjobController@testingcron']);
Route::get('dailyMail',['as' => 'dailyMail','uses' => 'CronjobController@dailyMail']);
Route::get('weeklyMail',['as' => 'weeklyMail','uses' => 'CronjobController@weeklyMail']);

Route::get('sentMail',['as' => 'sentMail','uses' => 'MailController@MailForm']);
Route::get('testMail',['as' => 'testMail','uses' => 'MailController@testMailForm']);
Route::get('SendMailReport',['as' => 'SendMailReport','uses' => 'MailController@SendMailReport']);

Route::get('pdfview',array('as'=>'pdfview','uses'=>'MailController@SendMailReport'));

Route::get('benchmarking',['as' => 'benchmarking','uses' => 'BenchMarkController@benchmarking']);

Route::get('getAllBench',['as' => 'getAllBench','uses' => 'BenchMarkController@getAllBench']);

Route::get('scheduleChange',['as' => 'scheduleChange','uses' => 'MailController@scheduleChange']);

Route::get('getMail',['as' => 'getMail','uses' => 'MailController@getMail']);
Route::get('MailPageSummary',['as' => 'MailPageSummary','uses' => 'MailController@MailPageSummary']);
Route::get('getMailMention',['as' => 'getMailMention','uses' => 'MailController@getMailMention']);
Route::get('getSentimentDetail',['as' => 'getSentimentDetail','uses' => 'MailController@getSentimentDetail']);
Route::get('getMailPostTag',['as' => 'getMailPostTag','uses' => 'MailController@getMailPostTag']);
Route::get('getBankType',['as' => 'getBankType','uses' => 'HomeController@getBankType']);

Route::get('DateTest',['as' => 'DateTest','uses' => 'MongoCRUDController@DateTest']);
Route::get('handle',['as' => 'handle','uses' => 'MongoCRUDController@handle']);
Route::get('autoTagging',['as' => 'autoTagging','uses' => 'HomeController@autoTagging']);
Route::get('updateByAutoTag',['as' => 'updateByAutoTag','uses' => 'HomeController@updateByAutoTag']);

Route::get('chargesAndRates',['as' => 'chargesAndRates','uses' => 'HomeController@chargesAndRates']);
Route::get('getExchangeRates',['as' => 'getExchangeRates','uses' => 'BankController@getExchangeRates']);
Route::get('getCallDeposit',['as' => 'getCallDeposit','uses' => 'BankController@getCallDeposit']);
Route::get('getfixedDeposit',['as' => 'getfixedDeposit','uses' => 'BankController@getfixedDeposit']);
Route::get('getIndustryPost',['as' => 'getIndustryPost','uses' => 'PageManageController@getIndustryPost']);
Route::get('getIndustryComment',['as' => 'getIndustryComment','uses' => 'PageManageController@getIndustryComment']);
Route::get('getAllCreditCard',['as' => 'getAllCreditCard','uses' => 'BankController@getAllCreditCard']);



Route::get('getGroupPost',['as' => 'getGroupPost','uses' => 'GroupController@getGroupPost']);
Route::get('getGroupComment',['as' => 'getGroupComment','uses' => 'GroupController@getGroupComment']);

Route::get('getRelatedGroupPosts',['as' => 'getRelatedGroupPosts','uses' => 'GroupController@getRelatedGroupPosts']);
Route::get('group_post',['as' => 'group_post','uses' => 'GroupController@index']);

Route::get('exchange_store',['as' => 'exchange_store','uses' => 'BankController@exchange_store']);

// just for testing Highlighted voice Cron
Route::get('insertHighlightedComment',['as' => 'insertHighlightedComment','uses' => 'MongoCRUDController@insertHighlightedComment']);

Route::get('get_highlighted_page_name',['as' => 'get_highlighted_page_name','uses' => 'CronjobController@get_highlighted_page_name']);

Route::get('bind_exchangeData',['as' => 'bind_exchangeData','uses' => 'BankController@bind_exchangeData']);
Route::get('bind_fixDepoData',['as' => 'bind_fixDepoData','uses' => 'BankController@bind_fixDepoData']);

Route::get('exchangeEntry',['as' => 'exchangeEntry','uses' => 'BankController@exchangeEntry']);
Route::get('fixedDepositEntry',['as' => 'fixedDepositEntry','uses' => 'BankController@fixedDepositEntry']);


Route::post('setMentionPredict',['as' => 'setMentionPredict','uses' => 'mentionDataController@setMentionPostPredict']);
Route::post('setArticlePredict',['as' => 'setArticlePredict','uses' => 'mentionDataController@setArticlePredict']);
Route::get('auth/{provider}', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');

// Route::get('/', ['as' => '/','uses' => 'HomeController@index']);
Route::get('/', ['as' => 'brand','uses' => 'HomeController@index']);

/*Auth::routes();*/
Route::get('login', ['as' => 'login','uses' => 'Auth\LoginController@showLoginForm']);
Route::get('landing', ['as' => 'landing','uses' => 'Auth\LoginController@LandingPage']);
Route::post('login',['as' => '','uses' => 'Auth\LoginController@login']);

Route::get('comment', ['as' => 'updateComment','uses' => 'MongoCRUDController@commentUpdate']);

Route::get('tag',['as' => 'MakeTag','uses' => 'MongoCRUDController@doTag']);

Route::get('upload_asr',['as' => 'upload_asr','uses' => 'tagsController@upload_asr']);

// Password Reset Routes...
Route::post('password/email', [
  'as' => 'password.email',
  'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail'
]);
Route::get('password/reset', [
  'as' => 'password.request',
  'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
]);
Route::post('password/reset', [
  'as' => '',
  'uses' => 'Auth\ResetPasswordController@reset'
]);
Route::get('password/reset/{token}', [
  'as' => 'password.reset',
  'uses' => 'Auth\ResetPasswordController@showResetForm'
]);
Route::get('register', [
  'as' => 'register',
  'uses' => 'Auth\RegisterController@showRegistrationForm'
]);
Route::post('register', [
  'as' => '',
  'uses' => 'Auth\RegisterController@register'
]);

Route::post('register_out', [
  'as' => '',
  'uses' => 'Auth\RegisterController@register_out'
]);

Route::get('register_out', [
  'as' => 'register_out',
  'uses' => 'Auth\RegisterController@showOutRegistrationForm'
]);


Route::group(['middleware' => 'auth'], function () {
 
  Route::post('/notification/tag/notification','tagsController@notification');
  

Route::get('gethiddendiv', [
  'as'   => 'gethiddendiv',
  'uses' => 'HomeController@gethiddendiv'
]);

Route::get('getCronStatus', [
  'as'   => 'getCronStatus',
  'uses' => 'HomeController@getCronStatus'
]);


Route::get('pointoutmention', [
  'as'   => 'pointoutmention',
  'uses' => 'HomeController@pointoutmention'
]);

Route::get('pointoutcomment', [
  'as'   => 'pointoutcomment',
  'uses' => 'HomeController@pointoutcomment'
]);
Route::get('pointoutpost', [
  'as'   => 'pointoutpost',
  'uses' => 'HomeController@pointoutpost'
]);

Route::get('brand_store', [
  'as'   => 'brand_store',
  'uses' => 'ProjectController@brandStore'
]);
Route::post('campaign_store', [
  'as'   => 'campaign_store',
  'uses' => 'CampaignController@Store'
]);

Route::get('brand_update', [
  'as'   => 'brand_update',
  'uses' => 'ProjectController@brandUpdate'
]);
Route::post('campaign_update/', [
  'as'   => 'campaign_update',
  'uses' => 'CampaignController@Update'
]);

// Route::get('wordcloud',['as'=>'wordcloud','uses' => 'WordCloudController@index']);
Route::resource('wordcloud','WordCloudController');


Route::get('brandList/edit/{id}', [
  'as'   => 'brandList/edit',
  'uses' => 'ProjectController@brandEdit'
]);

Route::get('campaignlist', [
  'as'   => 'campaignlist',
  'uses' => 'CampaignController@campaignlist'
]);
Route::get('get_campaignList', [
  'as'   => 'get_campaignList',
  'uses' => 'CampaignController@get_campaignList'
]);

Route::get('campaign/create', [
  'as'   => 'campaign/create',
  'uses' => 'CampaignController@Create'
]);
Route::get('audience', [
  'as'   => 'audience',
  'uses' => 'CampaignController@audience'
]);
Route::post('audience_store', [
  'as'   => 'audience_store',
  'uses' => 'CampaignController@audience_store'
]);
Route::get('campaign/edit/{id}', [
  'as'   => 'campaign/edit',
  'uses' => 'CampaignController@Edit'
]);
Route::get('campaign/delete/{id}', [
  'as'   => 'campaign/delete',
  'uses' => 'CampaignController@delete'
]);

Route::get('brandList/delete/{id}', [
  'as'   => 'brandList/delete',
  'uses' => 'ProjectController@brand_delete'
]);

Route::get('brandList/create', [
  'as'   => 'brandList/create',
  'uses' => 'ProjectController@brandCreate'
]);
Route::get('keyword-group/edit/{id}', [
  'as'   => 'keyword-group/edit',
  'uses' => 'ProjectKeywordController@edit'
]);
Route::get('otherkeyword-group/edit/{id}', [
  'as'   => 'otherkeyword-group/edit',
  'uses' => 'OtherKeywordController@edit'
]);

Route::get('keyword-group/delete/{group_name}', [
  'as'   => 'keyword-group/delete',
  'uses' => 'ProjectKeywordController@keywordGroup_delete'
]);

Route::get('otherkeyword-group/delete/{group_name}', [
  'as'   => 'otherkeyword-group/delete',
  'uses' => 'OtherKeywordController@keywordGroup_delete'
]);

Route::get('keyword-group/create', [
  'as'   => 'keyword-group/create',
  'uses' => 'ProjectKeywordController@create'
]);
Route::get('otherkeyword-group/create', [
  'as'   => 'otherkeyword-group/create',
  'uses' => 'OtherKeywordController@create'
]);
Route::post('keyword-group-store', [
  'as'   => 'keyword-group-store',
  'uses' => 'ProjectKeywordController@store'
]);
Route::get('otherkeyword-group-store', [
  'as'   => 'otherkeyword-group-store',
  'uses' => 'OtherKeywordController@store'
]);
Route::post('keyword_group_update', [
  'as'   => 'keyword_group_update',
  'uses' => 'ProjectKeywordController@update'
]);

resources/views/word_dict.blade.php
@extends('layouts',['project_data' => $project_data,'count'=>$count,'title'=>$title])
@section('content')
  <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
               
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                   <div class="row page-titles">
                    <div class="col-md-5 col-8 align-self-center">
                        <h4 class="text-themecolor m-b-0 m-t-0" style="padding-left:5px;padding-top:5px;font-weight: 500">Word Dictionary</h4>
                       <!--  <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                            <li class="breadcrumb-item active">Brand List</li>
                        </ol> -->
                    </div>



                </div>

      @if(!isset($data))

                @if(session()->has('message'))
            <div class="">
              {{ session()->get('message') }}
            </div>
          @endif
                <!-- Row -->
             <div class="row" >
                    <div class="col-12" >
                      
                        <div class="card" >
                            <div class="card-body">
                                <form role="form" class="" action="{{route('wordcloud.store')}}" method="post" id="myform">
                                  {{csrf_field()}}
                                  <div class="box-body">
                                    <div class="row">
                                       <table class="table">
                                        <input type='hidden' name='brand_id' value="{{ $brand_id }}">
                                        <td></td>
                                          <td > Word: </td>
                                          <td><input type="text" class="form-control form-control-line{{ $errors->has('word') ? ' is-invalid' : '' }}" value="{{ old('word') }}" name="word" id="word" autofocus placeholder="Enter word">
                                          @if ($errors->has('word'))
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('word') }}</strong>
                                                    </span>
                                                @endif
                                              </td> 
                                          <td><button type="submit" class="btn btn-flat btn-green pull-right" style="margin-left: 17px;"  value="">Save</button></td>
                                        </table>
                                     </div>
                                    </div>
                                </form> 
                              </div>
                            </div>            
                          </div>
                          </div>

      @else

        @if(session()->has('message'))
      <div class="">
        {{ session()->get('message') }}
      </div>
       @endif
              
                <!-- Row -->
             <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                        {!! Form::model($data, ['method' => 'PATCH','class'=>'form-material m-t-10','enctype'=>'multipart/form-data','route' => ['wordcloud.update', $data->id]]) !!}
                         {{csrf_field()}}
                                <div class="box-body">
                                    <div class="row">
                                       <table class="table">
                                        
                                        <input type="hidden" id="brand_id" name="brand_id" value="{{ old( 'name', $brand_id) }}" >
                                        <td></td>
                                          <td > Word: </td>
                                          <td><input type="text" class="form-control form-control-line{{ $errors->has('word') ? ' is-invalid' : '' }}" value="{{ old('word', $data->word) }}" name="word" id="word" autofocus>
                                          @if ($errors->has('word'))
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('word') }}</strong>
                                                    </span>
                                                @endif
                                              </td> 
                                          <td><button type="submit" class="btn btn-flat btn-green pull-right" style="margin-left: 17px;"  value="">Save</button></td>
                                        </table>
                                     </div>
                                    </div>
             {!! Form::close() !!}
                            </div>

                        </div>
                    </div>
                </div>
                          @endif
                         <div class="row">
                          <div class="col-12">
                            <div class="card">
                              <div class="card-body">
                                <h4 class="card-title">Words List</h4>
                                 <table id="words_table" class="table">
                                  <thead>
                                    <tr>
                                      <th>Word</th>
                                      <th>Created Time</th>
                                      <th></th>
                                    </tr>
                                  </thead>
                                </table>
                              </div>
                            </div>
                          </div>
                        </div>  
       
@endsection
@push('scripts')
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="{{asset('assets/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="{{asset('assets/plugins/popper/popper.min.js')}}" defer></script>
<script src="{{asset('assets/plugins/bootstrap/js/bootstrap.min.js')}}" defer></script>
<!-- slimscrollbar scrollbar JavaScript -->
<script src="{{asset('js/jquery.slimscroll.js')}}" defer></script>
<!--Wave Effects -->
<script src="{{asset('js/waves.js')}}" defer></script>
<!--Menu sidebar -->
<script src="{{asset('js/sidebarmenu.js')}}" defer></script>
<!--stickey kit -->
<script src="{{asset('assets/plugins/sticky-kit-master/dist/sticky-kit.min.js')}}" defer></script>
<script src="{{asset('assets/plugins/sparkline/jquery.sparkline.min.js')}}" defer></script>
<!--Custom JavaScript -->
<script src="{{asset('js/custom.min.js')}}" defer></script>
<!-- ============================================================== -->
<!-- This page plugins -->
<!-- ============================================================== -->



<!-- Chart JS -->
<script src="{{asset('assets/plugins/echarts/echarts.min.js')}}" defer></script>

<!-- Flot Charts JavaScript -->
<script src="{{asset('assets/plugins/flot/excanvas.js')}}" defer></script>
<script src="{{asset('assets/plugins/flot/jquery.flot.js')}}" defer></script>
<script src="{{asset('assets/plugins/flot/jquery.flot.time.js')}}" defer></script>
<script src="{{asset('assets/plugins/flot.tooltip/js/jquery.flot.tooltip.min.js')}}" defer></script>

<script src="{{asset('assets/plugins/moment/moment.js')}}" defer></script>
<script src="{{asset('assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js')}}" defer></script>

<script src="{{asset('assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js')}}" defer></script>
<!-- Date range Plugin JavaScript -->
<script src="{{asset('assets/plugins/timepicker/bootstrap-timepicker.min.js')}}" defer></script>
<script src="{{asset('assets/plugins/daterangepicker/daterangepicker.js')}}" defer></script>
<script src="{{asset('assets/plugins/moment/moment.js')}}" defer></script>

<!-- DataTables -->
  <!-- <script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('plugins/datatables/dataTables.bootstrap.min.js')}}"></script> -->
  <!-- This is data table -->
  <script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}" defer></script>

  <!-- ============================================================== -->
  <!-- Style switcher -->
  <!-- ============================================================== -->
  <!-- <script src="{{asset('assets/plugins/echarts/echarts.js')}}"></script> -->
  <script src="{{asset('assets/plugins/styleswitcher/jQuery.style.switcher.js')}}" defer></script>
  <script src="{{asset('assets/plugins/ion-rangeslider/js/ion-rangeSlider/ion.rangeSlider.min.js')}}" defer></script>
  <script src="{{asset('assets/plugins/ion-rangeslider/js/ion-rangeSlider/ion.rangeSlider-init.js')}}" defer></script>
  <script src="{{asset('assets/plugins/sweetalert2/sweetalert2.min.js')}}" defer></script>
     <script src="{{asset('plugins/iCheck/icheck.min.js')}}" defer></script>
     <script type="text/javascript">
     $(document).ready(function() {
  var GetURLParameter = function GetURLParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
    sURLVariables = sPageURL.split('&'),
    sParameterName,
    i;

    for (i = 0; i < sURLVariables.length; i++) {
      sParameterName = sURLVariables[i].split('=');

      if (sParameterName[0] === sParam) {
        return sParameterName[1] === undefined ? true : sParameterName[1];
      }
    }
  };

          $('#words_table').DataTable({
       "lengthChange": true,"info": false, "searching": true,
        processing: true,
        serverSide: false,
        "headers": {
          'X-CSRF-TOKEN': '{{csrf_token()}}' 
        },
         "ajax": {
          "url": '{{ route('getwordlist') }}',

 
         "data": {
            "brand_id":GetURLParameter("pid")
          }
 },
         columns: [
            {data: 'word',orderable: true, searchable: true},
            {data: 'created_at',orderable: true, searchable: false},
            {data: 'action', orderable: false, searchable: false}
        ]
        
    }).on('click', '.btn-delete[data-remote]', function (e) { 
        e.preventDefault();
         $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
          var url = $(this).data('remote');
      
                      swal({
              title: 'Are you sure?',
              text: "You won't be able to revert this!",
              type: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#3085d6',
              cancelButtonColor: '#d33',
              confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
              if (result.value) {
                   $.ajax({
                  url: url,
                  type: 'GET',
                  dataType: 'json',
                  data: {method: '_DELETE', submit: true,brand_id:GetURLParameter("pid")}
              }).always(function (data) {
                   $('#words_table').DataTable().rows().invalidate().draw();
                    window.location.reload()
                 
              });
             
              }
            })
      });





      });
  </script>
@endpush